name: Go CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Build the application
      run: go build -o weather main.go
